# Generated by Django 4.1.10 on 2023-07-13 13:14

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('commentaire', models.CharField(max_length=200, null=True)),
                ('nature', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('numero_ordre', models.CharField(max_length=100)),
            ],
        ),
    ]
